#!/bin/sh
set -e

if [ ! -e /container_started_already ]; then
	echo "127.0.0.1 localhost $VIRTUAL_HOST $(hostname)" >> /etc/hosts
	yes 'y' | sendmailconfig
	touch /container_started_already
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"