#!/bin/sh
set -e

if [ -z ${MAIL_HOST+x} ]; then 
	MAIL_HOST=$VIRTUAL_HOST 
fi

echo "127.0.0.1 localhost $MAIL_HOST $(hostname)" >> /etc/hosts
yes 'y' | sendmailconfig

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"